import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./(components)/NavBar";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Ticket App",
  description: "Generated by Thoby za",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`antialiased`}
      >
        <div className="h-screen flex flex-col max-h-screen w-full">
          <NavBar/>  
          <div className="flex-grow overflow-y-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
